[package]
name = "xit"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = { version = "0.38.0", features = [] }
ash-window = "0.13.0"
etagere = "0.2.13"
notify = "6.1.1"
swash = "0.1.17"
unicode-segmentation = "1.11.0"
winit = "0.30.3"
